// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/spotify.proto

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpotifyServiceClient is the client API for SpotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpotifyServiceClient interface {
	UpdateArtists(ctx context.Context, in *UpdateArtistsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type spotifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpotifyServiceClient(cc grpc.ClientConnInterface) SpotifyServiceClient {
	return &spotifyServiceClient{cc}
}

func (c *spotifyServiceClient) UpdateArtists(ctx context.Context, in *UpdateArtistsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/spotify.SpotifyService/UpdateArtists", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpotifyServiceServer is the server API for SpotifyService service.
// All implementations must embed UnimplementedSpotifyServiceServer
// for forward compatibility
type SpotifyServiceServer interface {
	UpdateArtists(context.Context, *UpdateArtistsRequest) (*empty.Empty, error)
	mustEmbedUnimplementedSpotifyServiceServer()
}

// UnimplementedSpotifyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSpotifyServiceServer struct {
}

func (UnimplementedSpotifyServiceServer) UpdateArtists(context.Context, *UpdateArtistsRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArtists not implemented")
}
func (UnimplementedSpotifyServiceServer) mustEmbedUnimplementedSpotifyServiceServer() {}

// UnsafeSpotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpotifyServiceServer will
// result in compilation errors.
type UnsafeSpotifyServiceServer interface {
	mustEmbedUnimplementedSpotifyServiceServer()
}

func RegisterSpotifyServiceServer(s grpc.ServiceRegistrar, srv SpotifyServiceServer) {
	s.RegisterService(&SpotifyService_ServiceDesc, srv)
}

func _SpotifyService_UpdateArtists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArtistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotifyServiceServer).UpdateArtists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/spotify.SpotifyService/UpdateArtists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotifyServiceServer).UpdateArtists(ctx, req.(*UpdateArtistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpotifyService_ServiceDesc is the grpc.ServiceDesc for SpotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spotify.SpotifyService",
	HandlerType: (*SpotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateArtists",
			Handler:    _SpotifyService_UpdateArtists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/spotify.proto",
}
