// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/spotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpotifyArtist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images []*SpotifyImage `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	Genres []string        `protobuf:"bytes,4,rep,name=genres,proto3" json:"genres,omitempty"`
}

func (x *SpotifyArtist) Reset() {
	*x = SpotifyArtist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotifyArtist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotifyArtist) ProtoMessage() {}

func (x *SpotifyArtist) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotifyArtist.ProtoReflect.Descriptor instead.
func (*SpotifyArtist) Descriptor() ([]byte, []int) {
	return file_proto_spotify_proto_rawDescGZIP(), []int{0}
}

func (x *SpotifyArtist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpotifyArtist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpotifyArtist) GetImages() []*SpotifyImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *SpotifyArtist) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type SpotifyRelease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images      []*SpotifyImage `protobuf:"bytes,3,rep,name=images,proto3" json:"images,omitempty"`
	ArtistIds   []string        `protobuf:"bytes,4,rep,name=artist_ids,json=artistIds,proto3" json:"artist_ids,omitempty"`
	ReleaseDate string          `protobuf:"bytes,5,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Genres      []string        `protobuf:"bytes,6,rep,name=genres,proto3" json:"genres,omitempty"`
}

func (x *SpotifyRelease) Reset() {
	*x = SpotifyRelease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spotify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotifyRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotifyRelease) ProtoMessage() {}

func (x *SpotifyRelease) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spotify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotifyRelease.ProtoReflect.Descriptor instead.
func (*SpotifyRelease) Descriptor() ([]byte, []int) {
	return file_proto_spotify_proto_rawDescGZIP(), []int{1}
}

func (x *SpotifyRelease) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpotifyRelease) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpotifyRelease) GetImages() []*SpotifyImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *SpotifyRelease) GetArtistIds() []string {
	if x != nil {
		return x.ArtistIds
	}
	return nil
}

func (x *SpotifyRelease) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *SpotifyRelease) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

type SpotifyImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width  int32  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height int32  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *SpotifyImage) Reset() {
	*x = SpotifyImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spotify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpotifyImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotifyImage) ProtoMessage() {}

func (x *SpotifyImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spotify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotifyImage.ProtoReflect.Descriptor instead.
func (*SpotifyImage) Descriptor() ([]byte, []int) {
	return file_proto_spotify_proto_rawDescGZIP(), []int{2}
}

func (x *SpotifyImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SpotifyImage) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SpotifyImage) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GetArtistRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetArtistRequest) Reset() {
	*x = GetArtistRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spotify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArtistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistRequest) ProtoMessage() {}

func (x *GetArtistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spotify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistRequest.ProtoReflect.Descriptor instead.
func (*GetArtistRequest) Descriptor() ([]byte, []int) {
	return file_proto_spotify_proto_rawDescGZIP(), []int{3}
}

func (x *GetArtistRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetArtistsForUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // This is a fanfuse user id
}

func (x *GetArtistsForUserRequest) Reset() {
	*x = GetArtistsForUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spotify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArtistsForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistsForUserRequest) ProtoMessage() {}

func (x *GetArtistsForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spotify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistsForUserRequest.ProtoReflect.Descriptor instead.
func (*GetArtistsForUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_spotify_proto_rawDescGZIP(), []int{4}
}

func (x *GetArtistsForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetArtistsForUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtistIds []string `protobuf:"bytes,1,rep,name=artist_ids,json=artistIds,proto3" json:"artist_ids,omitempty"` // These are spotify artist ids
}

func (x *GetArtistsForUserResponse) Reset() {
	*x = GetArtistsForUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spotify_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArtistsForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtistsForUserResponse) ProtoMessage() {}

func (x *GetArtistsForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spotify_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtistsForUserResponse.ProtoReflect.Descriptor instead.
func (*GetArtistsForUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_spotify_proto_rawDescGZIP(), []int{5}
}

func (x *GetArtistsForUserResponse) GetArtistIds() []string {
	if x != nil {
		return x.ArtistIds
	}
	return nil
}

type GetReleasesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArtistId string `protobuf:"bytes,1,opt,name=artist_id,json=artistId,proto3" json:"artist_id,omitempty"`
}

func (x *GetReleasesRequest) Reset() {
	*x = GetReleasesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spotify_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReleasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleasesRequest) ProtoMessage() {}

func (x *GetReleasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spotify_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleasesRequest.ProtoReflect.Descriptor instead.
func (*GetReleasesRequest) Descriptor() ([]byte, []int) {
	return file_proto_spotify_proto_rawDescGZIP(), []int{6}
}

func (x *GetReleasesRequest) GetArtistId() string {
	if x != nil {
		return x.ArtistId
	}
	return ""
}

type GetReleasesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Releases []*SpotifyRelease `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
}

func (x *GetReleasesResponse) Reset() {
	*x = GetReleasesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spotify_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReleasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReleasesResponse) ProtoMessage() {}

func (x *GetReleasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spotify_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReleasesResponse.ProtoReflect.Descriptor instead.
func (*GetReleasesResponse) Descriptor() ([]byte, []int) {
	return file_proto_spotify_proto_rawDescGZIP(), []int{7}
}

func (x *GetReleasesResponse) GetReleases() []*SpotifyRelease {
	if x != nil {
		return x.Releases
	}
	return nil
}

var File_proto_spotify_proto protoreflect.FileDescriptor

var file_proto_spotify_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x22, 0x7a,
	0x0a, 0x0d, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x70,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x22, 0xbd, 0x01, 0x0a, 0x0e, 0x53,
	0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x2d, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x70, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x22, 0x4e, 0x0a, 0x0c, 0x53, 0x70,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x33,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x46, 0x6f, 0x72, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x49, 0x64, 0x73, 0x22,
	0x31, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x49, 0x64, 0x22, 0x4a, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x72, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x70,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x32, 0x85,
	0x02, 0x0a, 0x0e, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x19,
	0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x70, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x41, 0x72, 0x74, 0x69, 0x73,
	0x74, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74,
	0x73, 0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x21, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x46, 0x6f, 0x72,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x70,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73,
	0x46, 0x6f, 0x72, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x53, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73,
	0x46, 0x6f, 0x72, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e, 0x73, 0x70, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_spotify_proto_rawDescOnce sync.Once
	file_proto_spotify_proto_rawDescData = file_proto_spotify_proto_rawDesc
)

func file_proto_spotify_proto_rawDescGZIP() []byte {
	file_proto_spotify_proto_rawDescOnce.Do(func() {
		file_proto_spotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_spotify_proto_rawDescData)
	})
	return file_proto_spotify_proto_rawDescData
}

var file_proto_spotify_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_spotify_proto_goTypes = []interface{}{
	(*SpotifyArtist)(nil),             // 0: spotify.SpotifyArtist
	(*SpotifyRelease)(nil),            // 1: spotify.SpotifyRelease
	(*SpotifyImage)(nil),              // 2: spotify.SpotifyImage
	(*GetArtistRequest)(nil),          // 3: spotify.GetArtistRequest
	(*GetArtistsForUserRequest)(nil),  // 4: spotify.GetArtistsForUserRequest
	(*GetArtistsForUserResponse)(nil), // 5: spotify.GetArtistsForUserResponse
	(*GetReleasesRequest)(nil),        // 6: spotify.GetReleasesRequest
	(*GetReleasesResponse)(nil),       // 7: spotify.GetReleasesResponse
}
var file_proto_spotify_proto_depIdxs = []int32{
	2, // 0: spotify.SpotifyArtist.images:type_name -> spotify.SpotifyImage
	2, // 1: spotify.SpotifyRelease.images:type_name -> spotify.SpotifyImage
	1, // 2: spotify.GetReleasesResponse.releases:type_name -> spotify.SpotifyRelease
	3, // 3: spotify.SpotifyService.GetArtist:input_type -> spotify.GetArtistRequest
	4, // 4: spotify.SpotifyService.GetArtistsForUser:input_type -> spotify.GetArtistsForUserRequest
	6, // 5: spotify.SpotifyService.GetReleasesForArtist:input_type -> spotify.GetReleasesRequest
	0, // 6: spotify.SpotifyService.GetArtist:output_type -> spotify.SpotifyArtist
	5, // 7: spotify.SpotifyService.GetArtistsForUser:output_type -> spotify.GetArtistsForUserResponse
	7, // 8: spotify.SpotifyService.GetReleasesForArtist:output_type -> spotify.GetReleasesResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_spotify_proto_init() }
func file_proto_spotify_proto_init() {
	if File_proto_spotify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_spotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotifyArtist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spotify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotifyRelease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spotify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpotifyImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spotify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArtistRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spotify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArtistsForUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spotify_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArtistsForUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spotify_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReleasesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_spotify_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReleasesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_spotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_spotify_proto_goTypes,
		DependencyIndexes: file_proto_spotify_proto_depIdxs,
		MessageInfos:      file_proto_spotify_proto_msgTypes,
	}.Build()
	File_proto_spotify_proto = out.File
	file_proto_spotify_proto_rawDesc = nil
	file_proto_spotify_proto_goTypes = nil
	file_proto_spotify_proto_depIdxs = nil
}
