// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: proto/spotify.proto

package proto

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateArtists is a request to update the artists for a user (this will be replaced with a proper update algorithm)
type UpdateArtistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *UpdateArtistsRequest) Reset() {
	*x = UpdateArtistsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_spotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArtistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArtistsRequest) ProtoMessage() {}

func (x *UpdateArtistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_spotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArtistsRequest.ProtoReflect.Descriptor instead.
func (*UpdateArtistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_spotify_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateArtistsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_spotify_proto protoreflect.FileDescriptor

var file_proto_spotify_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x14, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x5a, 0x0a, 0x0e,
	0x53, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48,
	0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x12,
	0x1d, 0x2e, 0x73, 0x70, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x72, 0x74, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_spotify_proto_rawDescOnce sync.Once
	file_proto_spotify_proto_rawDescData = file_proto_spotify_proto_rawDesc
)

func file_proto_spotify_proto_rawDescGZIP() []byte {
	file_proto_spotify_proto_rawDescOnce.Do(func() {
		file_proto_spotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_spotify_proto_rawDescData)
	})
	return file_proto_spotify_proto_rawDescData
}

var file_proto_spotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_spotify_proto_goTypes = []interface{}{
	(*UpdateArtistsRequest)(nil), // 0: spotify.UpdateArtistsRequest
	(*empty.Empty)(nil),          // 1: google.protobuf.Empty
}
var file_proto_spotify_proto_depIdxs = []int32{
	0, // 0: spotify.SpotifyService.UpdateArtists:input_type -> spotify.UpdateArtistsRequest
	1, // 1: spotify.SpotifyService.UpdateArtists:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_spotify_proto_init() }
func file_proto_spotify_proto_init() {
	if File_proto_spotify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_spotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArtistsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_spotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_spotify_proto_goTypes,
		DependencyIndexes: file_proto_spotify_proto_depIdxs,
		MessageInfos:      file_proto_spotify_proto_msgTypes,
	}.Build()
	File_proto_spotify_proto = out.File
	file_proto_spotify_proto_rawDesc = nil
	file_proto_spotify_proto_goTypes = nil
	file_proto_spotify_proto_depIdxs = nil
}
